apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: NotificationPubSub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  scopes:
    - review
    - notification
