apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reviewsecrets
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: C:\Users\AlbertoAnnunziata\Desktop\GAB\Frontend\components\secrets\review_secrets.json
  - name: nestedSeparator
    value: ":"
  - name: multiValued
    value: "false"
  scopes:
  - Review