on: [push]
name: Review Docker Image

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build review-api/ReviewApi -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/review:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/review:${{ github.sha }}
        
        - name: Deploy Container App
          uses: azure/container-apps-deploy-action@v0
          with:
            acrName: ${{ secrets.REGISTRY_NAME }}
            containerAppName: ${{ secrets.REVIEW_CONTAINERAPPSNAME }}
            resourceGroup: ${{ secrets.RESOURCE_GROUP }}
            imageToDeploy: ${{ secrets.REGISTRY_LOGIN_SERVER }}/review:${{ github.sha }}
          